version: "3.7"

services:
    # image project
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # mysql
    db:
        image: mysql:5.7.22
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-chase-cash}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_USER: ${DB_USERNAME:-root}
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    node:
        image: node:latest
        restart: unless-stopped
        working_dir: /var/www/
        command: ["npm", "run", "build"]
        volumes:
        - ./:/var/www
        networks:
        - laravel

    # phpmyadmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel
        depends_on:
            - db

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
